#! /bin/sh
echo "testing $0.."
set -e

. test/common

# Test != comparison fails
RESULT=""
EXPECT_RETURN=1 run_test --exists requires-version-1

# Test >=, > and = succeed
RESULT=""
run_test --exists requires-version-2

# Test <=, < and != succeed
RESULT=""
run_test --exists requires-version-3
